project:
  type: website
  output-dir: docs

resources:
  - "favicon.png"
  # - "CNAME"
  - "resources/*"
  - "articles/*"
  - "presentations/*"

website:
  title: "Papadopoulos Lab"
  site-url: "https://papadopoulos-lab.github.io"
  favicon: favicon.png
  navbar:
    left:
      - icon: resources/logo.png
        href: index.html
    right:
      - text: "Home"
        href: index.html
      - people.qmd
      - projects.qmd
      - publications.qmd
      - presentations.qmd
      - funding.qmd
      - blog.qmd
      - icon: github
        href: https://github.com/papadopoulos-lab
format:
  html:
    theme: litera
    css: styles.css
    title-block-banner: "#f8f8f8"
    title-block-banner-color: "#000000"


